name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      env:
        ANTHROPIC_API_KEY: test_key
        ALPACA_API_KEY: test_key
        ALPACA_SECRET_KEY: test_secret
        RUN_MODE: DRYRUN
      run: |
        pytest tests/test_rules.py -v --tb=short

    - name: Run linting (optional)
      continue-on-error: true
      run: |
        pip install ruff
        ruff check app/ --exit-zero

  docker-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        docker build -f docker/Dockerfile -t autotrader:test .

    - name: Test Docker image
      run: |
        docker run --rm autotrader:test python -c "import app; print('✓ Import successful')"
